server:
   port: 8888

logging:
    path: logs
    file: mylog.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://192.168.85.100:3306/course?serverTimezone=GMT
       username: 'root'
       password: '@123456Qw'

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*
